FROM node:16-alpine
WORKDIR /usr/src/kittychan_domain
COPY package.json .
RUN npm install -g typescript cpx
RUN npm install

ARG KITTY_CHAN_TOKEN
ENV KITTY_CHAN_TOKEN $KITTY_CHAN_TOKEN

ARG KITTY_CHAN_ID
ENV KITTY_CHAN_ID $KITTY_CHAN_ID

ARG DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_ID $DISCORD_CLIENT_ID

ARG DISCORD_CLIENT_SECRET
ENV DISCORD_CLIENT_SECRET $DISCORD_CLIENT_SECRET

ARG DISCORD_API
ENV DISCORD_API $DISCORD_API

ARG GRPC_URL
ENV GRPC_URL $GRPC_URL

ARG REDIS_HOST
ENV REDIS_HOST $REDIS_HOST

ARG REDIS_PASS
ENV REDIS_PASS $REDIS_PASS

ARG MONGO_URI
ENV MONGO_URI $MONGO_URI

ARG ES_HOST
ENV ES_HOST $ES_HOST

COPY . .
RUN tsc
RUN npm run build:proto
CMD ["node","./dist/main.js"]
EXPOSE 5030